// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUnuxq0cWiryh4roWT71y9dtiBDenGsSM',
    appId: '1:877913889649:web:5d8cdb677ac612890734d0',
    messagingSenderId: '877913889649',
    projectId: 'flutter-authentication-9ffd6',
    authDomain: 'flutter-authentication-9ffd6.firebaseapp.com',
    storageBucket: 'flutter-authentication-9ffd6.appspot.com',
    measurementId: 'G-96NTK8G408',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg3scX8_rdmOJGGleakNSA5wLYjvwBK84',
    appId: '1:877913889649:android:172cdcff236d6d180734d0',
    messagingSenderId: '877913889649',
    projectId: 'flutter-authentication-9ffd6',
    storageBucket: 'flutter-authentication-9ffd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJHPEJJ-ilBVl72_RVZAcg_tJiP67wdyY',
    appId: '1:877913889649:ios:5c1a1946c415352e0734d0',
    messagingSenderId: '877913889649',
    projectId: 'flutter-authentication-9ffd6',
    storageBucket: 'flutter-authentication-9ffd6.appspot.com',
    androidClientId: '877913889649-ujm8jtm759igibevs9uv5tanagcdko6c.apps.googleusercontent.com',
    iosClientId: '877913889649-2pshe4s978avc4nf9qq6d3go07im9no1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJHPEJJ-ilBVl72_RVZAcg_tJiP67wdyY',
    appId: '1:877913889649:ios:5c1a1946c415352e0734d0',
    messagingSenderId: '877913889649',
    projectId: 'flutter-authentication-9ffd6',
    storageBucket: 'flutter-authentication-9ffd6.appspot.com',
    androidClientId: '877913889649-ujm8jtm759igibevs9uv5tanagcdko6c.apps.googleusercontent.com',
    iosClientId: '877913889649-2pshe4s978avc4nf9qq6d3go07im9no1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUnuxq0cWiryh4roWT71y9dtiBDenGsSM',
    appId: '1:877913889649:web:9f7ddfdb3bf710cd0734d0',
    messagingSenderId: '877913889649',
    projectId: 'flutter-authentication-9ffd6',
    authDomain: 'flutter-authentication-9ffd6.firebaseapp.com',
    storageBucket: 'flutter-authentication-9ffd6.appspot.com',
    measurementId: 'G-PW9Q899TS2',
  );

}